name: "Really Busy Wizards"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile, Gemfile, Gemfile.lock, templates, post.thor, bin]

# Information for the Atom feed
gereksiz:
   author: "Justin Kenyon"
   email: "kenyonj@gmail.com"
   site: "http://justinkenyon.com"
